spring:
  profiles:
    active: [ des ]
  config:
    import: 

---
# Configuraciones que se aplican en el ambiente de desarrollo de la aplicación
server:
  port: 7090
spring:
  config:
    activate:
      on-profile: [ des ]
app:
  properties:
    app-private-properties:
      bar: Propiedad bar private desde desarrollo
      foo: Propiedad foo private desde desarrollo
    app-public-properties:
      bar: Propiedad bar private desde desarrollo
      foo: Propiedad foo private desde desarrollo

