server:
  port: 7090
spring:
  profiles:
    active: [ des ]

---
# Configuraciones que se aplican en el ambiente de desarrollo de la aplicaci贸n
spring:
  config:
    activate:
      on-profile: [ des ]
app:
  properties:
    foo: Propiedad foo desde desarrollo
    bar: Propiedad bar desde desarrollo

---
# Configuraciones que se aplican en el ambiente de producci贸n de la aplicaci贸n
spring:
  config:
    activate:
      on-profile: [ pro ]

---
# Configuraciones que se aplican en el ambiente de docker de la aplicaci贸n
spring:
  config:
    activate:
      on-profile: [ docker ]
    import: [ configtree:/run/secrets/ ]
