app:
  variable:
    mi-mensaje-en-texto-claro: Este mensaje es en texto claro :)
    mi-mensaje-encriptado: ENC(pCfabnZZCRd5yrDfaKrRgdsI5xm81t++qKyY5VDwGk5FADV6NJloyQ==)
jasypt:
  encryptor:
    bean: encryptorBean